[Interface]
PrivateKey = OAqG0lVQtm7EFAR0njjksLI54PH701Xq1ap7ZqDPJnI=
Address = 10.0.0.2/24
MTU = 1340
Table = off

[Peer]
PublicKey = J6U0vElJfN7NqwcFOOwBgLfLLqOhhK0V6zALAYLUaSs=
Endpoint = 35.209.103.156:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
